version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: circle_test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Wait for Database Connection
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - ruby/bundle-install
      - run:
          name: Load DB schema
          command: |
            cp .circleci/database.yml config/database.yml
            bundle exec rails db:schema:load RAILS_ENV=test
      - run:
          name: RSpec Tests
          command: bundle exec rspec
workflows:
  sample:
    jobs:
      - build
